baseURL = 'https://jpoly1219.github.io/'
languageCode = 'en-us'
title = "Jacob's Dev Blog"
theme = 'anatole'

[params]
    title = "Hi, I'm Jacob"
    author = "Jacob Kim"
    description = """
        Computer science student. Web developer. Gopher.
        Welcome to my personal dev blog :D
    """
    profilePicture = "profile.png"
    mainSections = ["posts"]
    postSectionName = "posts"

[menu]
    [[menu.main]]
    name = "Home"
    identifier = "home"
    weight = 100
    url = "/"

    [[menu.main]]
    name = "Posts"
    weight = 200
    identifier = "posts"
    url = "/posts/"

    [[menu.main]]
    name = "About"
    weight = 300
    identifier = "about"
    url = "/about/"

    [[menu.main]]
    name = "Portfolio"
    weight = 300
    identifier = "portfolio"
    url = "/portfolio/"

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false
